# Distance-based Algorithm & Similarity Metrics

Distance-based algorithms are machine learning algorithms that classify queries by computing distances between these queries and a number of internally stored exemplars.

In Milvus, similarity metrics are used to measure similarities among vectors. Choosing a good distance metric helps improve the classification and clustering performance significantly.

The following link shows how these widely used similarity metrics fit with various input data forms and Milvus indexes: [Milvus Similarity Metrics](https://milvus.io/docs/metric.md)

# Euclidian Distance (L2)

Euclidean distance measures the length of a segment that connects 2 points.

$$d(a,b) = d(b,a) = \sqrt{\Sigma_{i=0}^{n-1}(b_i - a_i)^2}$$

Where $a = (a0, a1,..., an-1)$ and $b = (b0, b1,..., bn-1)$ are two points in n-dimensional Euclidean space.

Milvus only caculates the value before applying square root when Euclidean distance is chosen as the distance metric.

In [5]:
# Python code to find Euclidean distance using linalg.norm()

import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# calculating Euclidean distance
# using linalg.norm()
dist = np.linalg.norm(point1 - point2)

# printing Euclidean distance
print(dist)

2.23606797749979


In [6]:
# Python code to find Euclidean distance using dot()

import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# subtracting vector
temp = point1 - point2

# doing dot product
# for finding
# sum of the squares
sum_sq = np.dot(temp.T, temp)

# Doing squareroot and
# printing Euclidean distance
print(np.sqrt(sum_sq))

2.23606797749979


In [7]:
# Python code to find Euclidean distance
# Using sum() and square()

import numpy as np

# Initialising points in numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# Finding sum of squares
sum_sq = np.sum(np.square(point1 - point2))

# Doing squareroot and printing Euclidean distance
print(np.sqrt(sum_sq))

2.23606797749979


In [1]:
import math

point_list = [
    [0, 0, 0],  # 0
    [6.888437030500963, 5.159088058806049, -1.5885683833831],
    [2.0667720363602307, 5.384582486178219, -3.4898856343748133],
    [7.742743817055683, 1.4508370077567676, -3.957946551327696],
    [9.410384606156306, 9.613094711663472, -3.864209434979891],
    [5.047141494150383, 14.72917879480795, -1.4968295014732576],
    [0.05726832139919402, 22.924103914172754, 8.158880019279806],
    [6.261613041330982, 30.96742292296441, 4.361831405666459],
    [10.858248006533554, 38.94418868232428, 8.041510043975286],
    [10.30110231558782, 30.958212843691598, 6.724946753050958],
    [12.518841784463852, 39.21843390844956, 16.057074108466132],
]

def dist(list):
    cummulativeDist = 0

    # iterate over sets of points
    for i in range(len(list) - 1):
        coordInit = list[i]
        coordFinal = list[i + 1]

        # distance from one pt to the next
        dist = math.sqrt(
            ((coordInit[0] - coordFinal[0]) ** 2)
            + ((coordInit[1] - coordFinal[2]) ** 2)
            + ((coordInit[2] - coordFinal[2]) ** 2)
        )

        cummulativeDist += dist

    return cummulativeDist


print(f"Distance: {dist(point_list)}")

Distance: 152.28944029130207


# Inner Product (IP)

The IP distance between two embeddings are defined as follows:
$$p(A,B) = A \cdot B = \sum^{n-1}_{i=0} a_i \cdot b_i$$
IP is more useful if you need to compare non-normalized data or when you care about magnitude and angle.

**Note:** If you apply the IP distance metric to normalized embeddings, the result will be equivalent to calculating the cosine similarity between the embeddings.

Suppose X' is normalized from embedding X:

$$X' = (x'_1, x'_2, \dots, x'_n), X' \in^n$$

The correlation between the two embeddings is as follows:

$$x'_i = \frac{x_i}{||X||} = \frac{x_i}{\sqrt{\sum_{i=1}^n(x_i)^2}}$$

In [2]:
# Importing library
import numpy as np

# Creating two 1-D arrays
array1 = np.array([6, 2])
array2 = np.array([2, 5])

print("Original 1-D arrays:")
print(array1)
print(array2)

# Output
print("Inner Product of the two array is:")
result = np.inner(array1, array2)
print(result)

Original 1-D arrays:
[6 2]
[2 5]
Inner Product of the two array is:
22


In [3]:
# Importing library
import numpy as np

# Creating two 1-D arrays
array1 = np.array([1, 3, 5])
array2 = np.array([0, 1, 5])

print("Original 1-D arrays:")
print(array1)
print(array2)

# Output
print("Inner Product of the two array is:")
result = np.inner(array1, array2)
print(result)

Original 1-D arrays:
[1 3 5]
[0 1 5]
Inner Product of the two array is:
28


# Cosine Similarity

Cosine similarity uses the cosine of the angle between two sets of vectors to measure how similar they are. You can think of the two sets of vectors as two line segments that start from the same origin ([0,0,...]) but point in different directions.

To calculate the cosine similarity between two sets of vectors $A = (a_0, a_1,..., a_{n-1})$ and $B = (b_0, b_1,..., b_{n-1})$, use the following formula:

$$\cos \theta=\frac{\sum_0^{n-1}\left(a_i \cdot b_i\right)}{\sqrt{\sum_0^{n-1} a_i^2} \cdot \sqrt{\sum_0^{n-1} b_i^2}}$$

Note: The cosine similarity is always in the interval $[-1, 1]$.

In [4]:
# import required libraries
import numpy as np
from numpy.linalg import norm

# define two lists or array
A = np.array([2, 1, 2, 3, 2, 9])
B = np.array([3, 4, 2, 4, 5, 5])

print("A:", A)
print("B:", B)

# compute cosine similarity
cosine = np.dot(A, B) / (norm(A) * norm(B))
print("Cosine Similarity:", cosine)

A: [2 1 2 3 2 9]
B: [3 4 2 4 5 5]
Cosine Similarity: 0.8188504723485274


In [5]:
# import required libraries
import numpy as np
from numpy.linalg import norm

# define two lists or array
A = np.array([[2, 1, 2], [3, 2, 9], [-1, 2, -3]])
B = np.array([3, 4, 2])
print("A:\n", A)
print("B:\n", B)

# compute cosine similarity
cosine = np.dot(A, B) / (norm(A, axis=1) * norm(B))
print("Cosine Similarity:\n", cosine)

A:
 [[ 2  1  2]
 [ 3  2  9]
 [-1  2 -3]]
B:
 [3 4 2]
Cosine Similarity:
 [ 0.86657824  0.67035541 -0.04962917]


# Jaccard Distance

**Jaccard similarity** coefficient measures the similarity between two sample sets and is defined as the cardinality of the intersection of the defined sets divided by the cardinality of the union of them. It can only be applied to finite sample sets.

$$J(A,B) = \frac{|A \cap B|}{|A| + |B| - |A\cap B|}$$

**Jaccard distance** measures the dissimilarity between data sets and is obtained by subtracting the Jaccard similarity coefficient from 1. For binary variables, Jaccard distance is equivalent to the Tanimoto coefficient.

$$d_j(A, B)=1-J(A, B)=\frac{|A \cup B|-|A \cap B|}{|A \cup B|}$$

In [6]:
def jaccard_similarity(set1, set2):
    # intersection of two sets
    intersection = len(set1.intersection(set2))
    # Unions of two sets
    union = len(set1.union(set2))

    return intersection / union


set_a = {"Geeks", "for", "Geeks", "NLP", "DSc"}
set_b = {"Geek", "for", "Geeks", "DSc.", "ML", "DSA"}

similarity = jaccard_similarity(set_a, set_b)
print("Jaccard Similarity:", similarity)

Jaccard Similarity: 0.25


In [7]:
def jaccard_distance(set1, set2):
    # Symmetric difference of two sets
    Symmetric_difference = set1.symmetric_difference(set2)
    # Unions of two sets
    union = set1.union(set2)

    return len(Symmetric_difference) / len(union)


set_a = {"Geeks", "for", "Geeks", "NLP", "DSc"}
set_b = {"Geek", "for", "Geeks", "DSc.", "ML", "DSA"}

distance = jaccard_distance(set_a, set_b)
print("Jaccard distance:", distance)

Jaccard distance: 0.75


In [9]:
import numpy as np
from sklearn.metrics import jaccard_score

# predicted values
y_pred = np.array([1, 1, 1, 0, 1]).reshape(-1, 1)
# true values
y_true = np.array([1, 1, 0, 0, 1]).reshape(-1, 1)

# Calculate Jaccard Index
jaccard_index = jaccard_score(y_true, y_pred)

# Calculate Jaccard Distance
jaccard_distance = 1 - jaccard_index

print("Jaccard Index:", jaccard_index)
print("Jaccard Distance:", jaccard_distance)

Jaccard Index: 0.75
Jaccard Distance: 0.25


# Hamming Distance

**Hamming Distance** measures the minimum number of substitutions required to change one string into the other, or equivalently, the minimum number of errors that could have transformed one string into the other. </br>

For more please see [wiki](https://en.wikipedia.org/wiki/Hamming_distance)

Define Hamming Distance in full functional form

In [8]:
def hamming_distance(string1: str, string2: str) -> int:
    """Return the Hamming distance between two strings."""
    if len(string1) != len(string2):
        raise ValueError("Strings must be of equal length.")
    dist_counter = 0
    for n in range(len(string1)):
        if string1[n] != string2[n]:
            dist_counter += 1
    return dist_counter

Short hand form

In [9]:
sum(char1 != char2 for char1, char2 in zip("user", "uses", strict=True))

1

In [10]:
hamming_distance("user", "uses")

1

# Structural Similarity

When a chemical structure occurs as a part of a larger chemical structure, the former is called a substructure and the latter is called a superstructure. For example, ethanol is a substructure of acetic acid, and acetic acid is a superstructure of ethanol.

Structural similarity is used to determine whether two chemical formulae are similar to each other in that one is the superstructure or substructure of the other.

To determine whether A is a *superstructure* of B, use the following formula:

$$D=(A \& B\bar=B) ? 0: \infty$$

Where:

- A is the binary representation of a chemical formula to be retrieved
- B is the binary representation of a chemical formula in the database
Once it returns 0, A is not a superstructure of B. Otherwise, the result is the other way around.

To determine whether A is a *substructure* of B, use the following formula:

$$D=(A \& B\bar=A) ? 0: \infty$$

Once it returns 0, A is not a substructure of B. Otherwise, the result is the other way around.